name: pages

on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Build module
        run: npx ng build ngx-iban --configuration production
      - name: Build demo page
        run: npx ng build demo-app --base-href=/ngx-iban/ --configuration production
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/demo-app
          force_orphan: true
          user_name: 'Mark Manders'
          user_email: 'mmjmanders@gmail.com'
