name: pages

on:
  push:
    branches:
      - main
    paths:
      - 'projects/demo-app/**'
      - 'projects/ngx-iban/package.json'

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/iron'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build module
        run: pnpm build ngx-iban

      - name: Build demo page
        run: pnpm build demo-app --base-href=/ngx-iban/

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/demo-app
          force_orphan: true
          user_name: 'Mark Manders'
          user_email: 'mmjmanders@gmail.com'
