name: publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/iron'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build module
        run: pnpm build ngx-iban

      - name: Publish package
        run: pnpm publish --no-git-checks ./dist/ngx-iban
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
