name: publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build module
        run: npx ng build ngx-iban --configuration production
      - name: Publish package
        run: npm publish ./dist/ngx-iban
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
